version: '3.9'

services:
  nginx_proxy:
    container_name: nginx_proxy
    image: "nginx_proxy"
    restart: on-failure
    depends_on:
      - react_app
      - node_app
    ports:
      - "80:80"
      
  node_app:
    container_name: node_app
    image: "node_app"
    restart: on-failure
    ports:
      - "3001:3001"

  react_app:
    container_name: react_app
    image: "react_app"
    restart: on-failure
    depends_on:
      - node_app
    ports:
      - "3000:3000"
