version: '3.9'

services:
  nginx:
    container_name: nginx
    image:
    restart: on-failure
    depends_on:
      - client
      - backend
    ports:
      - "80:80"
      
  backend:
    container_name: backend
    image: 
    restart: on-failure
    ports:
      - "3001:3001"

  client:
    container_name: client
    image: 
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "3000:3000"
